### ISSUE TITLE
Doesn't Compile Under microchip xc16 v1.25

### ISSUE THREAD

**Issue by dagoodma** [MatrixPilot/MatrixPilot#6]
I was unable to compile the matrix pilot auav3 project in MPLABX with xc16 v1.25 compiler. There was an error about missing <spi.h>. I did get it to compile and program under xc16 v1.22. Can this be mentioned somewhere in the README, mainly that the xc16 v1.22 compiler should be used?

**Comment by phollands** [comment]
David, it turns out that the version 1.25 XC16 compiler does not include the peripherals library. All previous versions did include the peripherals library. You can see my detailed response about this issue on the uavdevboard discussion group as the same issue has just cropped up for some one else.

https://groups.google.com/d/msg/uavdevboard/ejYKqyt9zEA/DB7xe0RVAAAJ
